/**
 * @file src/consts/env.js
 * @description Shared environment variable names, values, and warning codes.
 * @module consts/env
 */

export const ENV_VARS = Object.freeze({
  NODE_ENV: "NODE_ENV",
  JEST_WORKER_ID: "JEST_WORKER_ID",
  LOG_LEVEL: "LOG_LEVEL",
  PRETTY_LOGS: "PRETTY_LOGS",
  DISABLE_HOT_RELOAD: "DISABLE_HOT_RELOAD",
  ACTOR_WEB_SERVER_PORT: "ACTOR_WEB_SERVER_PORT",
  DUCKDB_STORAGE_DIR: "DUCKDB_STORAGE_DIR",
  DUCKDB_FILENAME: "DUCKDB_FILENAME",
  INPUT: "INPUT",
  NPM_PACKAGE_VERSION: "npm_package_version",
  APIFY_ACTOR_DIR: "APIFY_ACTOR_DIR",
  APIFY_LOCAL_STORAGE_DIR: "APIFY_LOCAL_STORAGE_DIR",
  APIFY_HOMEPAGE_URL: "APIFY_HOMEPAGE_URL",
  DUCKDB_MEMORY_LIMIT: "DUCKDB_MEMORY_LIMIT",
  DUCKDB_VACUUM_ENABLED: "DUCKDB_VACUUM_ENABLED",
  CUSTOM_SCRIPT_WORKER_MAX_OLD_GENERATION_MB:
    "CUSTOM_SCRIPT_WORKER_MAX_OLD_GENERATION_MB",
  CUSTOM_SCRIPT_WORKER_MAX_YOUNG_GENERATION_MB:
    "CUSTOM_SCRIPT_WORKER_MAX_YOUNG_GENERATION_MB",
});

export const ENV_VALUES = Object.freeze({
  TEST: "test",
  PRODUCTION: "production",
});

export const ENV_WARNING_CODES = Object.freeze({
  PROJECT_ENV_LOAD_FAILED: "PROJECT_ENV_LOAD_FAILED",
});
